### ISSUE TITLE
zip og tar.gz knapper gjør ingenting

### ISSUE THREAD

**Issue by ghost** [obtitus/barnehagefakta_osm_data#2]
Hvis jeg klikker på "zip" og "tar.gz"-knappene vist på bildet under så får jeg bare ned master-branchen med readme og license. Skulle de gitt meg alle barnehagefilene ?

![firefox_2018-09-27_09-56-41](https://user-images.githubusercontent.com/1347494/46131412-
da87ec00-c23b-11e8-838c-098cec63852e.png)

Hvis ikke de skulle det , er det tilgjengelig et annet sted?

**Comment by obtitus** [comment]
Fixed the link so that the download points to gh-pages branch and not master. This gives you the page source, there is a folder called data/ with all municipalities containing among other things .osm files for each municipalities. The download does not contain a single file with all kindergartens.
